/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Student;

/**
 *
 * @author aliff
 */
public class BookAppointment1 extends javax.swing.JFrame {

    /**
     * Creates new form BookAppointment1
     */
    public BookAppointment1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button1 = new Student.Button();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        button2 = new Student.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        button1.setBorder(null);
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setIcon(new javax.swing.ImageIcon("C:\\Users\\aliff\\Desktop\\UTHM SEM 3\\BIC20904 (OBJECT-ORIENTED PROGRAMMING)\\Arrows-Back-icon.png")); // NOI18N
        button1.setBorderColor(new java.awt.Color(255, 255, 255));
        button1.setColorClick(new java.awt.Color(199, 199, 199));
        button1.setColorOver(new java.awt.Color(239, 240, 241));
        button1.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(button1);
        button1.setBounds(403, 122, 48, 48);

        jTextField1.setBackground(new java.awt.Color(239, 240, 241));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jTextField1.setActionCommand("<Not Set>");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(419, 350, 602, 39);

        jTextField2.setBackground(new java.awt.Color(239, 240, 241));
        jTextField2.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jTextField2.setActionCommand("<Not Set>");
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(419, 435, 602, 39);

        jTextField3.setBackground(new java.awt.Color(239, 240, 241));
        jTextField3.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jTextField3.setActionCommand("<Not Set>");
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(419, 519, 602, 39);

        jTextField4.setBackground(new java.awt.Color(239, 240, 241));
        jTextField4.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jTextField4.setActionCommand("<Not Set>");
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(419, 611, 602, 39);

        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setText("Next");
        button2.setColor(new java.awt.Color(95, 182, 249));
        button2.setColorClick(new java.awt.Color(0, 105, 186));
        button2.setColorOver(new java.awt.Color(199, 199, 199));
        button2.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        button2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(button2);
        button2.setBounds(618, 683, 204, 66);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Book Appointment - 1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1440, 891);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 891));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookAppointment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookAppointment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookAppointment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookAppointment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookAppointment1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Student.Button button1;
    private Student.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
