/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Student;

import java.sql. *;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

public class LoginStudent extends javax.swing.JFrame {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;
private String CurrentUser;

    /**
     * Creates new form loginstudent
     */
    public LoginStudent() {
        initComponents();
        conn = ConnectJ.ConnectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        show_pass = new javax.swing.JCheckBox();
        signup_btn = new Student.Button();
        forgotpass_btn = new Student.Button();
        matric = new javax.swing.JTextField();
        pass_field = new javax.swing.JPasswordField();
        back_btn = new Student.Button();
        login_btn = new Student.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        show_pass.setText("SHOW");
        show_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_passMouseClicked(evt);
            }
        });
        show_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_passActionPerformed(evt);
            }
        });
        jPanel1.add(show_pass);
        show_pass.setBounds(948, 530, 60, 20);

        signup_btn.setBorder(null);
        signup_btn.setForeground(new java.awt.Color(54, 67, 252));
        signup_btn.setText("Sign Up");
        signup_btn.setColorClick(new java.awt.Color(199, 199, 199));
        signup_btn.setColorOver(new java.awt.Color(239, 240, 241));
        signup_btn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        signup_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signup_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_btnMouseClicked(evt);
            }
        });
        signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_btnActionPerformed(evt);
            }
        });
        jPanel1.add(signup_btn);
        signup_btn.setBounds(910, 580, 100, 30);

        forgotpass_btn.setBorder(null);
        forgotpass_btn.setForeground(new java.awt.Color(255, 51, 51));
        forgotpass_btn.setText("Forgot password?");
        forgotpass_btn.setBorderColor(new java.awt.Color(255, 255, 255));
        forgotpass_btn.setColorClick(new java.awt.Color(199, 199, 199));
        forgotpass_btn.setColorOver(new java.awt.Color(239, 240, 241));
        forgotpass_btn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jPanel1.add(forgotpass_btn);
        forgotpass_btn.setBounds(420, 568, 200, 50);

        matric.setBackground(new java.awt.Color(239, 240, 241));
        matric.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        matric.setActionCommand("<Not Set>");
        matric.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        matric.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(matric);
        matric.setBounds(419, 433, 602, 39);

        pass_field.setBackground(new java.awt.Color(239, 240, 241));
        pass_field.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        pass_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(pass_field);
        pass_field.setBounds(419, 522, 602, 39);

        back_btn.setBorder(null);
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Arrows-Back-icon.png"))); // NOI18N
        back_btn.setBorderColor(new java.awt.Color(255, 255, 255));
        back_btn.setColorClick(new java.awt.Color(199, 199, 199));
        back_btn.setColorOver(new java.awt.Color(239, 240, 241));
        back_btn.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        back_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });
        jPanel1.add(back_btn);
        back_btn.setBounds(400, 110, 48, 48);

        login_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        login_btn.setForeground(new java.awt.Color(255, 255, 255));
        login_btn.setText("Log in");
        login_btn.setColor(new java.awt.Color(95, 182, 249));
        login_btn.setColorClick(new java.awt.Color(0, 105, 186));
        login_btn.setColorOver(new java.awt.Color(199, 199, 199));
        login_btn.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        login_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        login_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btnMouseClicked(evt);
            }
        });
        jPanel1.add(login_btn);
        login_btn.setBounds(618, 629, 204, 66);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Log-in [Student].png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1400, 890);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_btnActionPerformed

    private void show_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_passActionPerformed
        // TODO add your handling code here:
        if(show_pass.isSelected())
            pass_field.setEchoChar((char)0);
        else
            pass_field.setEchoChar('*');
    }//GEN-LAST:event_show_passActionPerformed

    private void show_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_passMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_show_passMouseClicked

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        // TODO add your handling code here:
        MainLogin start = new MainLogin();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btnMouseClicked

    private void signup_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_btnMouseClicked
        // TODO add your handling code here:
        RegisterStudent start = new RegisterStudent();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signup_btnMouseClicked

    private void login_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseClicked
       
        String sql = "SELECT * FROM reg_student WHERE MatricNo=? AND Pass=?";
        
        try{
            
            pst = conn.prepareStatement(sql);
            
            pst.setString(1,matric.getText()); //matric no
            pst.setString(2,pass_field.getText()); //password
            
            rs = pst.executeQuery();
            
            if (rs.next()){
                JOptionPane.showMessageDialog(null, " Successfully Login!");
                new MainPage().setVisible(true);
                new LoginStudent().setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "Matric No or Password is not correct!");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        //reset field
        matric.setText("");
        pass_field.setText("");
    }//GEN-LAST:event_login_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Student.Button back_btn;
    private Student.Button forgotpass_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private Student.Button login_btn;
    private javax.swing.JTextField matric;
    private javax.swing.JPasswordField pass_field;
    private javax.swing.JCheckBox show_pass;
    private Student.Button signup_btn;
    // End of variables declaration//GEN-END:variables
}
