/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Student;

/**
 *
 * @author aliff
 */
public class MainLogin extends javax.swing.JFrame {

    /**
     * Creates new form mainlogin
     */
    public MainLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        admin_btn = new Student.Button();
        lect_btn = new Student.Button();
        student_btn = new Student.Button();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        admin_btn.setForeground(new java.awt.Color(255, 255, 255));
        admin_btn.setText("Admin");
        admin_btn.setColor(new java.awt.Color(95, 182, 249));
        admin_btn.setColorClick(new java.awt.Color(0, 105, 186));
        admin_btn.setColorOver(new java.awt.Color(199, 199, 199));
        admin_btn.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        admin_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        admin_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_btnMouseClicked(evt);
            }
        });
        jPanel1.add(admin_btn);
        admin_btn.setBounds(618, 485, 204, 66);

        lect_btn.setForeground(new java.awt.Color(255, 255, 255));
        lect_btn.setText("Lecturer");
        lect_btn.setColor(new java.awt.Color(95, 182, 249));
        lect_btn.setColorClick(new java.awt.Color(0, 105, 186));
        lect_btn.setColorOver(new java.awt.Color(199, 199, 199));
        lect_btn.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        lect_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lect_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lect_btnMouseClicked(evt);
            }
        });
        lect_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lect_btnActionPerformed(evt);
            }
        });
        jPanel1.add(lect_btn);
        lect_btn.setBounds(618, 565, 204, 66);

        student_btn.setForeground(new java.awt.Color(255, 255, 255));
        student_btn.setText("Student");
        student_btn.setColor(new java.awt.Color(95, 182, 249));
        student_btn.setColorClick(new java.awt.Color(0, 105, 186));
        student_btn.setColorOver(new java.awt.Color(199, 199, 199));
        student_btn.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        student_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        student_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                student_btnMouseClicked(evt);
            }
        });
        student_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_btnActionPerformed(evt);
            }
        });
        jPanel1.add(student_btn);
        student_btn.setBounds(618, 645, 204, 66);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Log-in [Main].png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1440, 891);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 891));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lect_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lect_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lect_btnActionPerformed

    private void student_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_btnActionPerformed

    private void student_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_student_btnMouseClicked
        // TODO add your handling code here:
        LoginStudent start = new LoginStudent();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_student_btnMouseClicked

    private void lect_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lect_btnMouseClicked
        // TODO add your handling code here:
        LoginLecturer start = new LoginLecturer();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lect_btnMouseClicked

    private void admin_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_btnMouseClicked
        // TODO add your handling code here:
        LoginAdmin start = new LoginAdmin();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_admin_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Student.Button admin_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private Student.Button lect_btn;
    private Student.Button student_btn;
    // End of variables declaration//GEN-END:variables
}
