/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Student;

import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;


/**
 *
 * @author aliff
 */
public class MyProfile extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form MyProfile
     */
    public MyProfile() {
        initComponents();
        conn = ConnectJ.ConnectDB();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        matric = new javax.swing.JTextField();
        fname_field = new javax.swing.JTextField();
        mobilenum_field = new javax.swing.JTextField();
        email_field = new javax.swing.JTextField();
        search_details = new javax.swing.JTextField();
        back_btn = new Student.Button();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        matric.setBackground(new java.awt.Color(239, 240, 241));
        matric.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        matric.setActionCommand("<Not Set>");
        matric.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        matric.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(matric);
        matric.setBounds(220, 240, 602, 39);

        fname_field.setBackground(new java.awt.Color(239, 240, 241));
        fname_field.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        fname_field.setActionCommand("<Not Set>");
        fname_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        fname_field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(fname_field);
        fname_field.setBounds(220, 340, 602, 39);

        mobilenum_field.setBackground(new java.awt.Color(239, 240, 241));
        mobilenum_field.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        mobilenum_field.setActionCommand("<Not Set>");
        mobilenum_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        mobilenum_field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(mobilenum_field);
        mobilenum_field.setBounds(220, 450, 602, 39);

        email_field.setBackground(new java.awt.Color(239, 240, 241));
        email_field.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        email_field.setActionCommand("<Not Set>");
        email_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        email_field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(email_field);
        email_field.setBounds(220, 570, 602, 39);

        search_details.setBackground(new java.awt.Color(239, 240, 241));
        search_details.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        search_details.setActionCommand("<Not Set>");
        search_details.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        search_details.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        search_details.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_detailsKeyReleased(evt);
            }
        });
        jPanel1.add(search_details);
        search_details.setBounds(1120, 50, 190, 39);

        back_btn.setBorder(null);
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Arrows-Back-icon.png"))); // NOI18N
        back_btn.setBorderColor(new java.awt.Color(255, 255, 255));
        back_btn.setColorClick(new java.awt.Color(199, 199, 199));
        back_btn.setColorOver(new java.awt.Color(239, 240, 241));
        back_btn.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        back_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn);
        back_btn.setBounds(80, 90, 48, 48);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jLabel3.setText("Enter Matric Number:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(880, 40, 240, 50);

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1440, 891);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 891));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        // TODO add your handling code here:
        MainPage start = new MainPage();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btnMouseClicked

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    private void search_detailsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_detailsKeyReleased
        // TODO add your handling code here:
        String sql = "SELECT * FROM reg_student WHERE MatricNo=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, search_details.getText());
            rs = pst.executeQuery();
            while(rs.next()){
                matric.setText(rs.getString(2));
                fname_field.setText(rs.getString(4));
                mobilenum_field.setText(rs.getString(5));
                email_field.setText(rs.getString(6));
              
                matric.setEditable(false);
                fname_field.setEditable(false);
                mobilenum_field.setEditable(false);
                email_field.setEditable(false);
            }
        }catch(Exception e){           
        }
    }//GEN-LAST:event_search_detailsKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Student.Button back_btn;
    private javax.swing.JTextField email_field;
    private javax.swing.JTextField fname_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField matric;
    private javax.swing.JTextField mobilenum_field;
    private javax.swing.JTextField search_details;
    // End of variables declaration//GEN-END:variables
}
