/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Student;
import java.sql. *;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
/**
 *
 * @author aliff
 */
public class noregisterstudent extends javax.swing.JFrame {
Connection conn = null;
    /**
     * Creates new form registerstudent
     */
    public noregisterstudent() {
        initComponents();
        conn = ConnectJ.ConnectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button1 = new Student.Button();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        button3 = new Student.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 632));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jPanel1MouseWheelMoved(evt);
            }
        });
        jPanel1.setLayout(null);

        button1.setBorder(null);
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setIcon(new javax.swing.ImageIcon("C:\\Users\\aliff\\Desktop\\UTHM SEM 3\\BIC20904 (OBJECT-ORIENTED PROGRAMMING)\\Arrows-Back-icon.png")); // NOI18N
        button1.setBorderColor(new java.awt.Color(255, 255, 255));
        button1.setColorClick(new java.awt.Color(199, 199, 199));
        button1.setColorOver(new java.awt.Color(239, 240, 241));
        button1.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1);
        button1.setBounds(400, 90, 48, 48);

        jTextField1.setBackground(new java.awt.Color(239, 240, 241));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jTextField1.setActionCommand("<Not Set>");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(419, 328, 602, 39);

        jTextField2.setBackground(new java.awt.Color(239, 240, 241));
        jTextField2.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jTextField2.setActionCommand("<Not Set>");
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(419, 419, 602, 39);

        jTextField3.setBackground(new java.awt.Color(239, 240, 241));
        jTextField3.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jTextField3.setActionCommand("<Not Set>");
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(419, 501, 602, 39);

        jTextField4.setBackground(new java.awt.Color(239, 240, 241));
        jTextField4.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jTextField4.setActionCommand("<Not Set>");
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(419, 735, 602, 39);

        jTextField5.setBackground(new java.awt.Color(239, 240, 241));
        jTextField5.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jTextField5.setActionCommand("<Not Set>");
        jTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jTextField5);
        jTextField5.setBounds(419, 819, 602, 39);

        jTextField6.setBackground(new java.awt.Color(239, 240, 241));
        jTextField6.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        jTextField6.setActionCommand("<Not Set>");
        jTextField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jTextField6);
        jTextField6.setBounds(419, 914, 602, 39);
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(424, 1001, 20, 20);

        button3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setText("Register");
        button3.setColor(new java.awt.Color(95, 182, 249));
        button3.setColorClick(new java.awt.Color(0, 105, 186));
        button3.setColorOver(new java.awt.Color(199, 199, 199));
        button3.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        button3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(button3);
        button3.setBounds(610, 1052, 204, 66);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\aliff\\Desktop\\UTHM SEM 3\\BIC20904 (OBJECT-ORIENTED PROGRAMMING)\\Blank UI (1)\\Register Student.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1440, 1270);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void jPanel1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jPanel1MouseWheelMoved
        int h = jPanel1.getHeight();
        int a = evt.getWheelRotation();
        int x = jPanel1.getX();
        int y = jPanel1.getY();
        int b = 0;
        if (a>0){
            if(y==this.getHeight()-jPanel1.getHeight())
            {
                a=0;
            }
            else{
                b+=30;
                jPanel1.setLocation(x, y-b);
                b=0;
            }
        }
        if (a<0){
            if(y==0)
            {
                a=0;
            }
            else{
                b+=30;
                jPanel1.setLocation(x, y+b);
                b=0;
            }
        }
    }//GEN-LAST:event_jPanel1MouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(noregisterstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(noregisterstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(noregisterstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(noregisterstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new noregisterstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Student.Button button1;
    private Student.Button button3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
