/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Student;

import java.sql. *;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

public class RegisterStudent extends javax.swing.JFrame {
Connection conn = null;
    /**
     * Creates new form RegisterStudent
     */
    public RegisterStudent() {
        initComponents();
        conn = ConnectJ.ConnectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        show_pass1 = new javax.swing.JCheckBox();
        show_pass2 = new javax.swing.JCheckBox();
        fname_field = new javax.swing.JTextField();
        mobilenum_field = new javax.swing.JTextField();
        register_matric = new javax.swing.JTextField();
        email_field = new javax.swing.JTextField();
        reg_btn = new Student.Button();
        pass_field = new javax.swing.JPasswordField();
        confirmpass_field = new javax.swing.JPasswordField();
        back_btn = new Student.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        show_pass1.setText("SHOW");
        show_pass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_pass1MouseClicked(evt);
            }
        });
        show_pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_pass1ActionPerformed(evt);
            }
        });
        jPanel1.add(show_pass1);
        show_pass1.setBounds(640, 530, 60, 20);

        show_pass2.setText("SHOW");
        show_pass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_pass2MouseClicked(evt);
            }
        });
        show_pass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_pass2ActionPerformed(evt);
            }
        });
        jPanel1.add(show_pass2);
        show_pass2.setBounds(640, 610, 60, 20);

        fname_field.setBackground(new java.awt.Color(239, 240, 241));
        fname_field.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        fname_field.setActionCommand("<Not Set>");
        fname_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        fname_field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(fname_field);
        fname_field.setBounds(734, 429, 602, 39);

        mobilenum_field.setBackground(new java.awt.Color(239, 240, 241));
        mobilenum_field.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        mobilenum_field.setActionCommand("<Not Set>");
        mobilenum_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        mobilenum_field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(mobilenum_field);
        mobilenum_field.setBounds(734, 520, 602, 39);

        register_matric.setBackground(new java.awt.Color(239, 240, 241));
        register_matric.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        register_matric.setActionCommand("<Not Set>");
        register_matric.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        register_matric.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(register_matric);
        register_matric.setBounds(103, 429, 602, 39);

        email_field.setBackground(new java.awt.Color(239, 240, 241));
        email_field.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        email_field.setActionCommand("<Not Set>");
        email_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        email_field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(email_field);
        email_field.setBounds(734, 602, 602, 39);

        reg_btn.setForeground(new java.awt.Color(255, 255, 255));
        reg_btn.setText("Register");
        reg_btn.setColor(new java.awt.Color(95, 182, 249));
        reg_btn.setColorClick(new java.awt.Color(0, 105, 186));
        reg_btn.setColorOver(new java.awt.Color(199, 199, 199));
        reg_btn.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        reg_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reg_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reg_btnMouseClicked(evt);
            }
        });
        jPanel1.add(reg_btn);
        reg_btn.setBounds(618, 685, 204, 66);

        pass_field.setBackground(new java.awt.Color(239, 240, 241));
        pass_field.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        pass_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(pass_field);
        pass_field.setBounds(103, 520, 602, 39);

        confirmpass_field.setBackground(new java.awt.Color(239, 240, 241));
        confirmpass_field.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        confirmpass_field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(confirmpass_field);
        confirmpass_field.setBounds(103, 602, 602, 39);

        back_btn.setBorder(null);
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Arrows-Back-icon.png"))); // NOI18N
        back_btn.setBorderColor(new java.awt.Color(255, 255, 255));
        back_btn.setColorClick(new java.awt.Color(199, 199, 199));
        back_btn.setColorOver(new java.awt.Color(239, 240, 241));
        back_btn.setFont(new java.awt.Font("Arial", 1, 23)); // NOI18N
        back_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn);
        back_btn.setBounds(90, 138, 48, 48);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Register Student.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1440, 891);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 891));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void show_pass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_pass1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_show_pass1MouseClicked

    private void show_pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_pass1ActionPerformed
        // TODO add your handling code here:
        if(show_pass1.isSelected())
        pass_field.setEchoChar((char)0);
        else
        pass_field.setEchoChar('*');
    }//GEN-LAST:event_show_pass1ActionPerformed

    private void show_pass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_pass2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_show_pass2MouseClicked

    private void show_pass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_pass2ActionPerformed
        // TODO add your handling code here:
        if(show_pass2.isSelected())
        confirmpass_field.setEchoChar((char)0);
        else
        confirmpass_field.setEchoChar('*');
    }//GEN-LAST:event_show_pass2ActionPerformed

    private void reg_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_btnMouseClicked
        String matricno = register_matric.getText();
        String pass = pass_field.getText();
        String name = fname_field.getText();
        String mobno = mobilenum_field.getText();
        String email = email_field.getText();
        
        //validate either password is same
        if(!(new String(pass_field.getPassword()).equals(new String(confirmpass_field.getPassword())))){
            JOptionPane.showMessageDialog(null, "Password do not match!");
        }
        //check valid mobile no
        else if(!(mobno.matches("^[0-9]*$")&&mobno.length()<=15)){
            JOptionPane.showMessageDialog(null, "Invalid mobile number!");
        }
        //check blank space
        else if(matricno.equals("")||pass.equals("")||name.equals("")||mobno.equals("")||email.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill in the blank space details");
        }
        else{
            try{
            Statement s = conn.createStatement();
            s.executeUpdate("INSERT INTO reg_student(MatricNo, Pass, FullName, MobileNo, Email) "
                + "VALUES ('"+matricno+"','"+pass+"','"+name+"','"+mobno+"','"+email+"')");
            
            JOptionPane.showMessageDialog(null, "Account Successfully Created");
                //go to login
                this.setVisible(false); // close RegisterStudent
                new LoginStudent().setVisible(true); //open LoginStudent
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          }
        }
        //to reset field
        register_matric.setText("");
        pass_field.setText("");
        confirmpass_field.setText("");
        fname_field.setText("");
        mobilenum_field.setText("");
        email_field.setText("");
    
    }//GEN-LAST:event_reg_btnMouseClicked

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        // TODO add your handling code here:
        LoginStudent start = new LoginStudent();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btnMouseClicked

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Student.Button back_btn;
    private javax.swing.JPasswordField confirmpass_field;
    private javax.swing.JTextField email_field;
    private javax.swing.JTextField fname_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mobilenum_field;
    private javax.swing.JPasswordField pass_field;
    private Student.Button reg_btn;
    private javax.swing.JTextField register_matric;
    private javax.swing.JCheckBox show_pass1;
    private javax.swing.JCheckBox show_pass2;
    // End of variables declaration//GEN-END:variables
}
